In [2]:
import numpy as np


In [2]:
#Exercice 1:Array Creation and Manipulation
arr1 = np.arange(10)
print(arr1)


[0 1 2 3 4 5 6 7 8 9]


In [3]:
#Exercise 2:Type Conversion and Array Operations
lst = [3.14, 2.17, 0, 1, 2]
arr2 = np.array(lst, dtype=int)
print(arr2)


[3 2 0 1 2]


In [4]:
#Exercise 3:  Working with Multi-Dimensional Arrays
arr3 = np.arange(1, 10).reshape(3, 3)
print(arr3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
arr4 = np.random.rand(4, 5)
print(arr4)


[[0.42997757 0.81937311 0.85689409 0.72036418 0.7407452 ]
 [0.98786439 0.75317899 0.73114022 0.79657714 0.79906018]
 [0.37221053 0.64623527 0.46320967 0.36914928 0.39485247]
 [0.58605354 0.06268066 0.76242592 0.92488359 0.93199953]]


In [3]:
#Exercise 5 : Indexing Arrays
array = np.array([[21,22,23,22,22],
                  [20,21,22,23,24],
                  [21,22,23,22,22]])

second_row = array[1]
second_row



array([20, 21, 22, 23, 24])

In [4]:
#Exercise 6 : Reversing elements
arr = np.arange(10)
reversed_arr = arr[::-1]
reversed_arr


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [5]:
#Exercise 7 : Identity Matrix
identity = np.eye(4)
identity


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
#Exercise 9 : Create Array and Change its Structure
arr = np.arange(1, 21).reshape(4, 5)
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [7]:
#Exercise 10 : Conditional Selection of Values
arr = np.arange(10)
odd_numbers = arr[arr % 2 != 0]
odd_numbers


array([1, 3, 5, 7, 9])